### ISSUE TITLE
mission3_miles

### ISSUE THREAD

**Issue by jihyun-p** [SMUMC-7th/7th_Android#10]
## Issue

이슈 내용: 3주차 미션

## Branch Name

생성 브랜치 이름 : miles-flo-clone

## To-Do List

- [x] 키워드 작성
- [x] 강의 듣기
- [x] 강의 실습 따라하기
- [x] [SongActivity]화면 반복재생, 전체재생 이미지 교체해보기
- [x] [MainActivity]에 있는 MiniPlayer에 있는 데이터로 [SongActivity]화면 렌더링
- [x] [AlbumFragment]화면 내 취향 MIX 버튼 클릭시 이미지 변경해보기
