### ISSUE TITLE
mission3_rio

### ISSUE THREAD

**Issue by calla1102** [SMUMC-7th/7th_Android#12]
## Issue

이슈 내용: Chapter3 스터디

## Branch Name

생성 브랜치 이름 : rio_flo

## To-Do List

- [x] 유데미 3주차까지 실습 끝내기
- [x] **3주차 미션** __ Activity 전환(MainActivity ↔ SongActivity) 구현하기
- [x] **3주차 미션** __ Fragment 전환(HomeFragment ↔ AlbumFragment) 구현하기
- [x] **3주차 미션** __ [SongActivity]화면 반복재생, 전체재생 이미지 교체하기
- [x] **3주차 미션** __  [MainActivity]에 있는 MiniPlayer에 있는 데이터로 [SongActivity]화면 렌더링
- [x] **3주차 미션** __ [AlbumFragment]화면 내 취향 MIX 버튼 클릭시 이미지 변경해보기
- [x] **3주차 미션** __ Viewpager 구현하기
