### ISSUE TITLE
mission3_robin

### ISSUE THREAD

**Issue by dongwonyang** [SMUMC-7th/7th_Android#8]
## Issue

이슈 내용: week3 mission

## Branch Name

생성 브랜치 이름 :  robin

## To-Do List

- [x] keyword essential 작성
- [x] 강의 듣기
- [x] 기존 파일에서 SongActivity와 AlbumFragment 추가하기
- [x] Activity 전환(MainActivity ↔ SongActivity) 구현하기
- [x] Fragment 전환(HomeFragment ↔ AlbumFragment) 구현하기
- [x] Activity - Activity 간의 데이터 전달 및 클릭 시 이미지 변경
- [ ] Viewpager, indicatior 구현
